// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingredients.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getIngredientByID = `-- name: GetIngredientByID :one
SELECT id, fdc_id, open_food_facts_id, name, name_slug, food_group, default_unit_id, data_sources, created_at, updated_at FROM ingredients WHERE id = $1
`

func (q *Queries) GetIngredientByID(ctx context.Context, id pgtype.UUID) (Ingredient, error) {
	row := q.db.QueryRow(ctx, getIngredientByID, id)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.FdcID,
		&i.OpenFoodFactsID,
		&i.Name,
		&i.NameSlug,
		&i.FoodGroup,
		&i.DefaultUnitID,
		&i.DataSources,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIngredientBySlug = `-- name: GetIngredientBySlug :one
SELECT id, fdc_id, open_food_facts_id, name, name_slug, food_group, default_unit_id, data_sources, created_at, updated_at FROM ingredients WHERE name_slug = $1
`

func (q *Queries) GetIngredientBySlug(ctx context.Context, nameSlug string) (Ingredient, error) {
	row := q.db.QueryRow(ctx, getIngredientBySlug, nameSlug)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.FdcID,
		&i.OpenFoodFactsID,
		&i.Name,
		&i.NameSlug,
		&i.FoodGroup,
		&i.DefaultUnitID,
		&i.DataSources,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIngredientDensity = `-- name: GetIngredientDensity :one
SELECT id, ingredient_id, density_g_per_ml, notes, created_at, updated_at FROM ingredient_densities
WHERE ingredient_id = $1 AND (notes IS NULL OR notes = '')
LIMIT 1
`

func (q *Queries) GetIngredientDensity(ctx context.Context, ingredientID pgtype.UUID) (IngredientDensity, error) {
	row := q.db.QueryRow(ctx, getIngredientDensity, ingredientID)
	var i IngredientDensity
	err := row.Scan(
		&i.ID,
		&i.IngredientID,
		&i.DensityGPerMl,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIngredientDensityWithNotes = `-- name: GetIngredientDensityWithNotes :one
SELECT id, ingredient_id, density_g_per_ml, notes, created_at, updated_at FROM ingredient_densities
WHERE ingredient_id = $1 AND notes = $2
`

type GetIngredientDensityWithNotesParams struct {
	IngredientID pgtype.UUID `json:"ingredient_id"`
	Notes        pgtype.Text `json:"notes"`
}

func (q *Queries) GetIngredientDensityWithNotes(ctx context.Context, arg GetIngredientDensityWithNotesParams) (IngredientDensity, error) {
	row := q.db.QueryRow(ctx, getIngredientDensityWithNotes, arg.IngredientID, arg.Notes)
	var i IngredientDensity
	err := row.Scan(
		&i.ID,
		&i.IngredientID,
		&i.DensityGPerMl,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIngredientAllergens = `-- name: ListIngredientAllergens :many
SELECT a.name, ia.severity
FROM ingredient_allergens ia
JOIN allergens a ON a.id = ia.allergen_id
WHERE ia.ingredient_id = $1
`

type ListIngredientAllergensRow struct {
	Name     string `json:"name"`
	Severity string `json:"severity"`
}

func (q *Queries) ListIngredientAllergens(ctx context.Context, ingredientID pgtype.UUID) ([]ListIngredientAllergensRow, error) {
	rows, err := q.db.Query(ctx, listIngredientAllergens, ingredientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIngredientAllergensRow{}
	for rows.Next() {
		var i ListIngredientAllergensRow
		if err := rows.Scan(&i.Name, &i.Severity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngredientDietFlags = `-- name: ListIngredientDietFlags :many
SELECT df.name, idf.compatible
FROM ingredient_diet_flags idf
JOIN diet_flags df ON df.id = idf.diet_flag_id
WHERE idf.ingredient_id = $1
`

type ListIngredientDietFlagsRow struct {
	Name       string `json:"name"`
	Compatible bool   `json:"compatible"`
}

func (q *Queries) ListIngredientDietFlags(ctx context.Context, ingredientID pgtype.UUID) ([]ListIngredientDietFlagsRow, error) {
	rows, err := q.db.Query(ctx, listIngredientDietFlags, ingredientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIngredientDietFlagsRow{}
	for rows.Next() {
		var i ListIngredientDietFlagsRow
		if err := rows.Scan(&i.Name, &i.Compatible); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngredientNutrients = `-- name: ListIngredientNutrients :many
SELECT
    n.name AS nutrient_name,
    n.unit AS nutrient_unit,
    n.display_rank,
    n.is_displayed,
    nc.name AS category_name,
    inu.amount_per_100g
FROM ingredient_nutrients inu
JOIN nutrients n ON n.id = inu.nutrient_id
LEFT JOIN nutrient_categories nc ON nc.id = n.category_id
WHERE inu.ingredient_id = $1
ORDER BY n.display_rank
`

type ListIngredientNutrientsRow struct {
	NutrientName  string         `json:"nutrient_name"`
	NutrientUnit  string         `json:"nutrient_unit"`
	DisplayRank   int32          `json:"display_rank"`
	IsDisplayed   bool           `json:"is_displayed"`
	CategoryName  pgtype.Text    `json:"category_name"`
	AmountPer100g pgtype.Numeric `json:"amount_per_100g"`
}

func (q *Queries) ListIngredientNutrients(ctx context.Context, ingredientID pgtype.UUID) ([]ListIngredientNutrientsRow, error) {
	rows, err := q.db.Query(ctx, listIngredientNutrients, ingredientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIngredientNutrientsRow{}
	for rows.Next() {
		var i ListIngredientNutrientsRow
		if err := rows.Scan(
			&i.NutrientName,
			&i.NutrientUnit,
			&i.DisplayRank,
			&i.IsDisplayed,
			&i.CategoryName,
			&i.AmountPer100g,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngredients = `-- name: ListIngredients :many
SELECT id, fdc_id, open_food_facts_id, name, name_slug, food_group, default_unit_id, data_sources, created_at, updated_at FROM ingredients ORDER BY name LIMIT $1 OFFSET $2
`

type ListIngredientsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListIngredients(ctx context.Context, arg ListIngredientsParams) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, listIngredients, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ingredient{}
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.FdcID,
			&i.OpenFoodFactsID,
			&i.Name,
			&i.NameSlug,
			&i.FoodGroup,
			&i.DefaultUnitID,
			&i.DataSources,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchIngredients = `-- name: SearchIngredients :many
SELECT id, fdc_id, open_food_facts_id, name, name_slug, food_group, default_unit_id, data_sources, created_at, updated_at FROM ingredients
WHERE name ILIKE '%' || $1 || '%'
ORDER BY name
LIMIT $2
`

type SearchIngredientsParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) SearchIngredients(ctx context.Context, arg SearchIngredientsParams) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, searchIngredients, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ingredient{}
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.FdcID,
			&i.OpenFoodFactsID,
			&i.Name,
			&i.NameSlug,
			&i.FoodGroup,
			&i.DefaultUnitID,
			&i.DataSources,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
