// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddRecipeTag(ctx context.Context, arg AddRecipeTagParams) error
	// Collects all allergens for a recipe by traversing sub-recipes.
	CollectRecipeAllergens(ctx context.Context, recipeID pgtype.UUID) ([]string, error)
	// Determines diet compatibility: a recipe is compatible with a diet
	// only if ALL its ingredients explicitly have compatible=true for that flag.
	// Missing data (no row in ingredient_diet_flags) means NOT compatible.
	CollectRecipeDietFlags(ctx context.Context, recipeID pgtype.UUID) ([]string, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (AppUser, error)
	GetCompiledRecipe(ctx context.Context, recipeID pgtype.UUID) (GetCompiledRecipeRow, error)
	GetCompiledRecipeBySlug(ctx context.Context, slug string) (GetCompiledRecipeBySlugRow, error)
	GetIngredientByID(ctx context.Context, id pgtype.UUID) (Ingredient, error)
	GetIngredientBySlug(ctx context.Context, nameSlug string) (Ingredient, error)
	GetIngredientDensity(ctx context.Context, ingredientID pgtype.UUID) (IngredientDensity, error)
	GetIngredientDensityWithNotes(ctx context.Context, arg GetIngredientDensityWithNotesParams) (IngredientDensity, error)
	GetRecipeByID(ctx context.Context, id pgtype.UUID) (Recipe, error)
	GetRecipeBySlug(ctx context.Context, slug string) (Recipe, error)
	GetUnitByID(ctx context.Context, id pgtype.UUID) (Unit, error)
	GetUnitByName(ctx context.Context, name string) (Unit, error)
	GetUserByExternalID(ctx context.Context, externalID pgtype.Text) (AppUser, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (AppUser, error)
	ListAllRecipeIDs(ctx context.Context) ([]pgtype.UUID, error)
	ListCompiledRecipes(ctx context.Context, arg ListCompiledRecipesParams) ([]ListCompiledRecipesRow, error)
	ListIngredientAllergens(ctx context.Context, ingredientID pgtype.UUID) ([]ListIngredientAllergensRow, error)
	ListIngredientDietFlags(ctx context.Context, ingredientID pgtype.UUID) ([]ListIngredientDietFlagsRow, error)
	ListIngredientNutrients(ctx context.Context, ingredientID pgtype.UUID) ([]ListIngredientNutrientsRow, error)
	ListIngredients(ctx context.Context, arg ListIngredientsParams) ([]Ingredient, error)
	ListPublicRecipes(ctx context.Context, arg ListPublicRecipesParams) ([]Recipe, error)
	ListRecipeSteps(ctx context.Context, recipeID pgtype.UUID) ([]RecipeStep, error)
	ListRecipeTags(ctx context.Context, recipeID pgtype.UUID) ([]ListRecipeTagsRow, error)
	ListStaleRecipeIDs(ctx context.Context) ([]pgtype.UUID, error)
	ListStepComponents(ctx context.Context, stepID pgtype.UUID) ([]ListStepComponentsRow, error)
	ListUnits(ctx context.Context) ([]Unit, error)
	ListUnitsByDimension(ctx context.Context, dimension string) ([]Unit, error)
	ListUnitsBySystem(ctx context.Context, system string) ([]Unit, error)
	RemoveRecipeTag(ctx context.Context, arg RemoveRecipeTagParams) error
	// Resolves all leaf ingredients from a recipe's full sub-recipe tree
	// and aggregates total quantities per ingredient, normalizing to default unit.
	// Normalize quantities to each ingredient's default unit
	ResolveRecipeTree(ctx context.Context, recipeID pgtype.UUID) ([]ResolveRecipeTreeRow, error)
	SearchCompiledRecipes(ctx context.Context, arg SearchCompiledRecipesParams) ([]SearchCompiledRecipesRow, error)
	SearchIngredients(ctx context.Context, arg SearchIngredientsParams) ([]Ingredient, error)
	SearchPublicRecipes(ctx context.Context, arg SearchPublicRecipesParams) ([]Recipe, error)
	UpsertCompiledRecipe(ctx context.Context, arg UpsertCompiledRecipeParams) error
	UpsertTag(ctx context.Context, arg UpsertTagParams) (pgtype.UUID, error)
}

var _ Querier = (*Queries)(nil)
