// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: units.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUnitByID = `-- name: GetUnitByID :one
SELECT id, name, name_plural, system, dimension, to_base_factor, to_base_offset, created_at, updated_at FROM units WHERE id = $1
`

func (q *Queries) GetUnitByID(ctx context.Context, id pgtype.UUID) (Unit, error) {
	row := q.db.QueryRow(ctx, getUnitByID, id)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NamePlural,
		&i.System,
		&i.Dimension,
		&i.ToBaseFactor,
		&i.ToBaseOffset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnitByName = `-- name: GetUnitByName :one
SELECT id, name, name_plural, system, dimension, to_base_factor, to_base_offset, created_at, updated_at FROM units WHERE name = $1
`

func (q *Queries) GetUnitByName(ctx context.Context, name string) (Unit, error) {
	row := q.db.QueryRow(ctx, getUnitByName, name)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NamePlural,
		&i.System,
		&i.Dimension,
		&i.ToBaseFactor,
		&i.ToBaseOffset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUnits = `-- name: ListUnits :many
SELECT id, name, name_plural, system, dimension, to_base_factor, to_base_offset, created_at, updated_at FROM units ORDER BY system, dimension, name
`

func (q *Queries) ListUnits(ctx context.Context) ([]Unit, error) {
	rows, err := q.db.Query(ctx, listUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unit{}
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NamePlural,
			&i.System,
			&i.Dimension,
			&i.ToBaseFactor,
			&i.ToBaseOffset,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitsByDimension = `-- name: ListUnitsByDimension :many
SELECT id, name, name_plural, system, dimension, to_base_factor, to_base_offset, created_at, updated_at FROM units WHERE dimension = $1 ORDER BY system, name
`

func (q *Queries) ListUnitsByDimension(ctx context.Context, dimension string) ([]Unit, error) {
	rows, err := q.db.Query(ctx, listUnitsByDimension, dimension)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unit{}
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NamePlural,
			&i.System,
			&i.Dimension,
			&i.ToBaseFactor,
			&i.ToBaseOffset,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitsBySystem = `-- name: ListUnitsBySystem :many
SELECT id, name, name_plural, system, dimension, to_base_factor, to_base_offset, created_at, updated_at FROM units WHERE system = $1 ORDER BY dimension, name
`

func (q *Queries) ListUnitsBySystem(ctx context.Context, system string) ([]Unit, error) {
	rows, err := q.db.Query(ctx, listUnitsBySystem, system)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unit{}
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NamePlural,
			&i.System,
			&i.Dimension,
			&i.ToBaseFactor,
			&i.ToBaseOffset,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
