// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO app_users (display_name, email, preferred_unit_system, preferred_locale)
VALUES ($1, $2, $3, $4)
RETURNING id, external_id, display_name, email, preferred_unit_system, preferred_locale, created_at, updated_at
`

type CreateUserParams struct {
	DisplayName         string      `json:"display_name"`
	Email               pgtype.Text `json:"email"`
	PreferredUnitSystem string      `json:"preferred_unit_system"`
	PreferredLocale     string      `json:"preferred_locale"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.DisplayName,
		arg.Email,
		arg.PreferredUnitSystem,
		arg.PreferredLocale,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.DisplayName,
		&i.Email,
		&i.PreferredUnitSystem,
		&i.PreferredLocale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByExternalID = `-- name: GetUserByExternalID :one
SELECT id, external_id, display_name, email, preferred_unit_system, preferred_locale, created_at, updated_at FROM app_users WHERE external_id = $1
`

func (q *Queries) GetUserByExternalID(ctx context.Context, externalID pgtype.Text) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByExternalID, externalID)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.DisplayName,
		&i.Email,
		&i.PreferredUnitSystem,
		&i.PreferredLocale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, external_id, display_name, email, preferred_unit_system, preferred_locale, created_at, updated_at FROM app_users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.DisplayName,
		&i.Email,
		&i.PreferredUnitSystem,
		&i.PreferredLocale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
